//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Championship_Spanish
{
    using System;
    using System.Collections.Generic;
    
    public partial class Players
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Players()
        {
            this.TeamFights = new HashSet<TeamFights>();
        }
    
        public int id { get; set; }
        public string FIO { get; set; }
        public string Country { get; set; }
        public Nullable<int> NumberPlayer { get; set; }
        public string Position { get; set; }
        public Nullable<int> Team { get; set; }
    
        public virtual Teams Teams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamFights> TeamFights { get; set; }
    }
}
