//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Championship_Spanish
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamFights
    {
        public int id { get; set; }
        public Nullable<int> Team1 { get; set; }
        public Nullable<int> Team2 { get; set; }
        public Nullable<int> CountGoal1 { get; set; }
        public Nullable<int> CountGoal2 { get; set; }
        public Nullable<int> PlayerGoal { get; set; }
        public Nullable<System.DateTime> MatchDate { get; set; }
        public Nullable<int> CountWin { get; set; }
        public Nullable<int> CountLose { get; set; }
    
        public virtual Players Players { get; set; }
        public virtual Teams Teams { get; set; }
        public virtual Teams Teams1 { get; set; }
    }
}
